name: Fix styling

on:
  push:
    branches:
      - main
    paths:
      - '**.php'

jobs:
  pint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.1.0

      - name: Commit pint changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
